[package]
name = "zellij-tab-name"
version = "0.4.2"
authors = ["Ben Bachem <10088265+bezbac@users.noreply.github.com>"]
edition = "2018"

[dependencies]
zellij-tile = "0.40.1"
chrono = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strfmt = "0.2"
